name: PR Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Node.js artifacts
        uses: actions/setup-node@v3
        with:
          node-version: '19.3'
      - run: |
          cd site
          npm ci
          npm run build --if-present
      - name: Upload artifacts for plan
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/out

  plan:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts from build
      uses: actions/download-artifact@v3
      with:
        name: site
    - name: Test step to show dir contents
      run: ls -l
    - name: Download and run terraform
      run: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform.zip
        cd infra
        terraform init
        terraform plan -out=plan
